version: "3.5"

services:
  # Install postgres and setup the student database.
  postgres:
    container_name: dracarys
    image: debezium/postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=familydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test

