CREATE TABLE FAMILY (
    ID SERIAL NOT NULL PRIMARY KEY,
    SSN CHARACTER VARYING NOT NULL,
    TYPE CHARACTER VARYING NOT NULL,
    CREATED timestamp without time zone DEFAULT now()
);

ALTER SEQUENCE FAMILY_ID_SEQ RESTART WITH 101;
ALTER TABLE FAMILY REPLICA IDENTITY FULL;

CREATE TABLE ASSET (
    ID SERIAL NOT NULL PRIMARY KEY,
    MSISDN CHARACTER VARYING NOT NULL,
    CREATED timestamp without time zone DEFAULT now()
);

ALTER SEQUENCE ASSET_ID_SEQ RESTART WITH 1001;
ALTER TABLE ASSET REPLICA IDENTITY FULL;

CREATE TABLE COMMAND (
    ID SERIAL NOT NULL PRIMARY KEY,
    COMMAND_CLASS VARCHAR NOT NULL,
    COMMAND VARCHAR NOT NULL,
    CREATED timestamp without time zone DEFAULT now()
);

ALTER SEQUENCE COMMAND_ID_SEQ RESTART WITH 2001;
ALTER TABLE COMMAND REPLICA IDENTITY FULL;
